macro (set_build_location PROJECTS_ROOT_DIR)

    string(TOLOWER "../output/${TARGET_OS}/qt.${QT_VERSION}/${CMAKE_CXX_COMPILER_ID}-${CMAKE_CXX_COMPILER_VERSION}/${PROCESSOR_BIT}/${CMAKE_BUILD_TYPE}" OUTPUT_PATH)
    set(ROOT_BUILD_LOCATION "${PROJECTS_ROOT_DIR}/${OUTPUT_PATH}")

    set (macro_args ${ARGN})
    list(LENGTH macro_args num_args)
    if (${num_args} GREATER 0)
        list(GET macro_args 0 SUB_BUILD_FOLDER)
        set (BUILD_LOCATION "${ROOT_BUILD_LOCATION}/${SUB_BUILD_FOLDER}")
    else ()
        set (BUILD_LOCATION "${ROOT_BUILD_LOCATION}")
    endif ()

    set(EXECUTABLE_OUTPUT_PATH ${BUILD_LOCATION})
    set(LIBRARY_OUTPUT_PATH ${BUILD_LOCATION})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${BUILD_LOCATION})
    set(CMAKE_PDB_OUTPUT_DIRECTORY ${BUILD_LOCATION})

    target_link_directories(${PROJECT_NAME} PRIVATE ${ROOT_BUILD_LOCATION} ${BUILD_LOCATION})

    message ("-- Target name: \"${PROJECT_NAME}\"  version: ${PROJECT_VERSION}")
    message ("-- Binaries output direcory: ${BUILD_LOCATION}")

    if(WIN32)
      set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${BUILD_LOCATION})
      set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${BUILD_LOCATION})
      set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${BUILD_LOCATION})
      set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${BUILD_LOCATION})

      set(CMAKE_PDB_OUTPUT_DIRECTORY_DEBUG ${BUILD_LOCATION})
      set(CMAKE_PDB_OUTPUT_DIRECTORY_MINSIZEREL ${BUILD_LOCATION})
      set(CMAKE_PDB_OUTPUT_DIRECTORY_RELEASE ${BUILD_LOCATION})
      set(CMAKE_PDB_OUTPUT_DIRECTORY_RELWITHDEBINFO ${BUILD_LOCATION})

      set(VS_DEBUGGER_WORKING_DIRECTORY ${BUILD_LOCATION})
    endif()

endmacro()
