if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set (TARGET_OS "unknown")
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    string(FIND "${CMAKE_AR}" "arm-linux-gnueabihf" GUNEABIHF_ARM_LINUX_INDEX REVERSE)
    if (GUNEABIHF_ARM_LINUX_INDEX EQUAL -1)
        set (TARGET_OS "linux-x86_64")
    else ()
        set (TARGET_OS "linux-arm")
    endif ()
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    set (TARGET_OS "unknown")
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set (TARGET_OS "windows")
endif()
